### ISSUE TITLE
1.4.5最后一题感觉有点问题

### ISSUE THREAD

**Issue by AaronHu13** [ikesnowy/Alg4-Solutions#1]
直观感受N^100是一个幂函数，2^N是一个指数函数。当N趋向于无穷大时，不应该时2^N更大嘛？我在网上也找到了一个链接在讨论这个问题
https://www.zybang.com/question/2793df0cee31766f5cd555d749c480ae.html
，老哥你帮忙看一下，我数学底子比较差，直接推有点费劲。

我也正在攻算法这本书，希望以后能和老哥多取经交流，谢谢！

P.S.  你的题解做的真好，比我前几天star的那个全多了

**Comment by ikesnowy** [comment]
@Aaron0813 
这里的近似可以认为是找到一个函数 g(x)，在 N>1 的区间内，有 g(x)>f(x) 恒成立。
那么这里的 f(x)=N^100/2^N，
由于当 N>1 时，2^N>2。
因此 f(x) < N^100 = g(x)。
所以 N^100/2^N ~ N^100。
注意这里给出的并不是 N^100 + 2^N，如果这样的话就会近似成为 2^N 了。

**Comment by AaronHu13** [comment]
哦~我才看明白，这个找的是上界啊。懂了懂了

**Comment by AaronHu13** [comment]
谢谢老哥！
